# Generated by Django 5.1 on 2024-09-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_report_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='project',
        ),
    ]
