# Generated by Django 5.1 on 2024-09-18 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_captchastore_remove_project_user_alter_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
